Release 2.5.0
nf-core/mhcquant pull request #284
Opened 2023-10-04 07:23 UTC by jonasscheid

- Support for brukers tdf format by adding tdf2mzml converter [#263](https://github.com/nf-core/mhcquant/issues/263)
- DeepLC retention time prediction
- MS2PIP peak intensity prediction
- Added OpenMS FileFilter to clean mzml after parsing to remove artifacts like empty spectra or precursors with charge 0 (optional)
- Made file extension check case insensitive
- Added option to provide a default comet parameters file
- Optimize resource allocations
- Update to latest template 2.10 [#282](https://github.com/nf-core/mhcquant/pull/282)
- Restructured quantification to make use of enhanced rescoring:
Before
![mhcquant_subway_old](https://github.com/nf-core/mhcquant/assets/43858870/36109887-d860-42a0-88e7-2d51ee03be0c)

After
![mhcquant_subway](https://github.com/nf-core/mhcquant/assets/43858870/7ed8e58d-6b02-49fa-8dd4-a35cb9c383fa)

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mhcquant/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/mhcquant _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-10-04 07:28 UTC, jonasscheid commented
test_quant and test_full run through locally. I need to adjust resource allocations / time limits. But first I want to gather the comments of reviews to bundle it

2023-10-04 08:30 UTC, mapo9 requested changes
Except for the minor cosmetic changes:
LGTM!

2023-10-04 08:30 UTC, mapo9 commented on README.md
> +```
should this example be in the output?

2023-10-04 08:30 UTC, mapo9 commented on subworkflows/local/quant.nf
> +                .map { group_meta, meta, mzml, idxml -> [group_meta, meta, mzml.file, idxml.file]}
```suggestion
                .map { group_meta, meta, mzml, idxml -> [group_meta, meta, mzml.file, idxml.file] }
```

2023-10-06 11:11 UTC, steffenlem requested changes

2023-10-06 11:11 UTC, steffenlem commented on modules/local/tdf2mzml.nf
> +    container "docker.io/mfreitas/tdf2mzml"
conda and singularity are not available here?

2023-10-06 11:11 UTC, steffenlem commented on nextflow.config
> +    deeplc_calibration_mode         = 'rt_bin'
We could change this to 'idx_bin' since it outperformed the 'rt_bin' calibration in most cases.

2023-10-07 20:49 UTC, jonasscheid commented on README.md
> +```
No these things are issues arising due to auto.merging of the new template... I'll check the affected files again 👍🏼

2023-10-07 20:49 UTC, jonasscheid commented on README.md
> +```
Same here, thanks good catch!

2023-10-07 20:54 UTC, jonasscheid commented on bin/check_samplesheet.py
> +    VALID_FORMATS = (".raw", ".mzml", ".d")
That is black formatting. Nothing I am allowed to do here, else linter test crashes :D

2023-10-09 14:06 UTC, mapo9 approved these changes

2023-10-09 14:06 UTC, mapo9 commented
LGTM! 🚀

2023-10-10 07:55 UTC, steffenlem approved these changes
Looks good!

2023-10-10 14:24 UTC, merged