Add ms2rescore module, remove ms2pip and deeplc modules
nf-core/mhcquant pull request #293
Opened 2023-11-29 12:31 UTC by jonasscheid

Addressing #288

- Adding MS2Rescore and deprecating MS2PIP and DeepLC modules, since they are incorporated in MS2Rescore
- Adding a couple of TODOs for an upcoming refactoring

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/mhcquant/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/mhcquant _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-11-30 14:25 UTC, jonasscheid commented on modules/local/openms_idfilter.nf
> +        // TODO: Fix such that [] emtpy list is provided as peptide filter, not null
I want to do a separate refactoring PR that covers more than the TODOs and needs some more work. So the PR history is cleaner. Its only dev, so it should be fine imo

2023-12-07 09:06 UTC, steffenlem requested changes
As far as I can see, ms2rescore makes the RT prediction on the merged idXMLs of multiple runs. Is this intentional?

2023-12-07 10:21 UTC, steffenlem approved these changes

2023-12-07 10:22 UTC, steffenlem commented
My test run should be finished tomorrow

2023-12-18 10:56 UTC, merged